temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/ChartController.cs
using System.Web.Mvc;

namespace Milton.Controllers
{
    public class ChartController : Controller
    {
        public ViewResult Chartist()
        {
            return View();
        }

        public ViewResult Chartjs()
        {
            return View();
        }

        public ViewResult Flot()
        {
            return View();
        }

        public ViewResult Morris()
        {
            return View();
        }

        public ViewResult NVD3()
        {
            return View();
        }

        public ViewResult Other()
        {
            return View();
        }
        
        public ViewResult Peity()
        {
            return View();
        }

        public ViewResult Sparkline()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/ComponentsController.cs
using System.Web.Mvc;

namespace Milton.Controllers
{
    public class ComponentsController : Controller
    {
        public ViewResult Carousel()
        {
            return View();
        }

        public ViewResult Grid()
        {
            return View();
        }

        public ViewResult NestableList()
        {
            return View("nestable-list");
        }

        public ViewResult RangeSliders()
        {
            return View();
        }

        public ViewResult SweetAlert()
        {
            return View();
        }

        public ViewResult Widgets()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/ExtrasController.cs
using System.Web.Mvc;

namespace Milton.Controllers
{
    public class ExtrasController : Controller
    {
        public ViewResult Calendar()
        {
            return View();
        }

        public ViewResult CommingSoon()
        {
            return View();
        }

        public ViewResult EmailTemplate()
        {
            return View();
        }

        public ViewResult Faqs()
        {
            return View();
        }

        public ViewResult Gallary()
        {
            return View();
        }

        public ViewResult Invoice()
        {
            return View();
        }

        public ViewResult Maintainance()
        {
            return View();
        }

        public ViewResult Pricing()
        {
            return View();
        }

        public new ViewResult Profile()
        {
            return View();
        }

        public ViewResult Team()
        {
            return View();
        }

        public ViewResult Timeline()
        {
            return View();
        }

        public ViewResult Treeview()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/FormsController.cs
namespace Milton.Controllers
{
    using System.Web.Mvc;

    public class FormsController : Controller
    {
        public ViewResult Advanced()
        {
            return View();
        }

        public ViewResult Elements()
        {
            return View();
        }

        public ViewResult SummerNotes()
        {
            return View();
        }

        public ViewResult Uploads()
        {
            return View();
        }

        public ViewResult Validations()
        {
            return View();
        }

        public ViewResult Wizard()
        {
            return View();
        }

        public ViewResult Wysiwig()
        {
            return View();
        }

        public ViewResult XEditable()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Milton.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult typography()
        {
            return View();
        }

        public ViewResult ComposeMail()
        {
            return View();
        }

        public ViewResult Inbox()
        {
            return View();
        }

        public ViewResult ReadMail()
        {
            return View();
        }

        public ViewResult Google()
        {
            return View();
        }

        public ViewResult Vector()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/IconsController.cs
namespace Milton.Controllers
{
    using System.Web.Mvc;

    public class IconsController : Controller
    {
        public ActionResult fontawesome()
        {
            return View();
        }

        public ViewResult glyphicons()
        {
            return View();
        }

        public ViewResult ionicons()
        {
            return View();
        }

        public ViewResult materialdesign()
        {
            return View();
        }

        public ViewResult themifyicon()
        {
            return View();
        }

        public ViewResult weather()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/PagesController.cs

namespace Milton.Controllers
{
    using System.Web.Mvc;

    public class PagesController : Controller
    {
        public ActionResult NotFound()
        {
            return View();
        }

        public ViewResult ServerError()
        {
            return View();
        }

        public ViewResult Blank()
        {
            return View();
        }

        public ViewResult ConfirmMail()
        {
            return View();
        }

        public ViewResult LockScreen()
        {
            return View();
        }

        public ViewResult Login()
        {
            return View();
        }

        public ViewResult RecoverPassword()
        {
            return View();
        }

        public ViewResult Register()
        {
            return View();
        }

        public ViewResult Action()
        {
            return View();
        }

        public ViewResult EmailAlert()
        {
            return View();
        }

        public ViewResult BillingEmail()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/TablesController.cs
namespace Milton.Controllers
{
    using System.Web.Mvc;

    public class TablesController : Controller
    {
        public ActionResult Basic()
        {
            return View();
        }

        public ViewResult Datatables()
        {
            return View();
        }

        public ViewResult Editable()
        {
            return View();
        }
        public ViewResult FooTable()
        {
            return View();
        }
        public ViewResult Responsive()
        {
            return View();
        }
        public ViewResult Tablesaw()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Controllers/UIController.cs
namespace Milton.Controllers
{
    using System.Web.Mvc;

    public class UIController : Controller
    {
        public ActionResult Bootstrap()
        {
            return View();
        }

        public ViewResult Buttons()
        {
            return View();
        }

        public ViewResult CheckboxRadio()
        {
            return View();
        }

        public ViewResult Modals()
        {
            return View();
        }

        public ViewResult Notification()
        {
            return View();
        }

        public ViewResult Panels()
        {
            return View();
        }

        public ViewResult Portlets()
        {
            return View();
        }

        public ViewResult ProgressBars()
        {
            return View();
        }

        public ViewResult Tabs()
        {
            return View();
        }
    }
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Views/Chart/Chartist.cshtml
@{
    ViewBag.Title = "Chartist";
}
@section contents {
    <link rel="stylesheet" href="../plugins/chartist/dist/chartist.min.css">
}
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <ol class="breadcrumb pull-right">
                <li><a href="#">Minton</a></li>
                <li><a href="#">Charts</a></li>
                <li class="active">Chartist</li>
            </ol>
            <h4 class="page-title">Chartist</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Advanced Smil Animations</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="smil-animations" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Simple line chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="simple-line-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Line Scatter Diagram</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="scatter-diagram" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Line chart with tooltips</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="line-chart-tooltips" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Line chart with area</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="chart-with-area" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Bi-polar Line chart with area only</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="bi-polar-line" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>SVG Path animation</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="svg-animation" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Line Interpolation / Smoothing</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="line-smoothing" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Different configuration for different series</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="different-series" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>SVG Animations chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Label placement chart.
            </p>
            <div id="svg-dot-animation" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Bi-polar bar chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="bi-polar-bar" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Overlapping bars on mobile</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="overlapping-bars" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Multi-line labels</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="multi-line-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Stacked bar chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="stacked-bar-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Horizontal bar chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="horizontal-bar-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Extreme responsive configuration</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="extreme-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Distributed series</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="distributed-series" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Label placement</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Label placement chart.
            </p>
            <div id="label-placement-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Animating a Donut with Svg.animate</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="animating-donut" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Simple pie chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Label placement chart.
            </p>
            <div id="simple-pie" class="ct-chart ct-golden-section simple-pie-chart-chartist"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Pie chart with custom labels</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Horizontal bar chart.
            </p>
            <div id="pie-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Gauge chart</b></h4>
            <p class="text-muted m-b-30 font-13">
                Example of Label placement chart.
            </p>
            <div id="gauge-chart" class="ct-chart ct-golden-section"></div>
        </div>
    </div>
</div>

@section scripts{
    <!--Chartist Chart-->
    <script src="~/plugins/chartist/dist/chartist.min.js"></script>
    <script src="~/Scripts/pages/jquery.chartist.init.js"></script>

    <script src="~/Scripts/jquery.core.js"></script>
    <script src="~/Scripts/jquery.app.js"></script>
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Views/Chart/Chartjs.cshtml
@{
    ViewBag.Title = "Chartjs";
}

@section contents {

}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <ol class="breadcrumb pull-right">
                <li><a href="#">Minton</a></li>
                <li><a href="#">Charts</a></li>
                <li class="active">Chartjs Charts</li>
            </ol>
            <h4 class="page-title">Chartjs Charts</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Line Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet1"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet1" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="lineChart" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Donut Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet2"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet2" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="doughnut" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Pie Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet3"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet3" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="pie" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Bar Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet4"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet4" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="bar" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Radar Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet7"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet7" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="radar" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark">
                    Polar area Chart
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet5"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet5" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <canvas id="polarArea" height="300"> </canvas>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <!-- Chart JS -->
    <script src="~/plugins/chart.js/chart.min.js"></script>
    <script src="~/Scripts/pages/jquery.chartjs.init.js"></script>

    <script src="~/Scripts/jquery.core.js"></script>
    <script src="~/Scripts/jquery.app.js"></script>
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Views/Chart/NVD3.cshtml
@{
    ViewBag.Title = "NVD3";
}

@section contents {
    <link href="~/plugins/nvd3/build/nv.d3.min.css" rel="stylesheet" type="text/css" />
}

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <ol class="breadcrumb pull-right">
                <li><a href="#">Minton</a></li>
                <li><a href="#">Charts</a></li>
                <li class="active">Nvd3 Charts</li>
            </ol>
            <h4 class="page-title">Nvd3 Charts</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Line Chart</b></h4>

            <div class="line-chart">
                <svg style="height:400px;width:100%"></svg>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Discrete Bar Chart</b></h4>

            <div class="bar-chart">
                <svg style="height:400px;width:100%"></svg>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Horizontal Grouped / Stacked Bar Chart</b></h4>

            <div class="multi-chart">
                <svg style="height:500px;width:100%"></svg>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Scatter chart</b></h4>

            <div class="scatter-chart">
                <svg style="height:500px;width:100%"></svg>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Pie Chart &amp; Donut Chart</b></h4>
            <div class="row">
                <div class="col-md-6">
                    <div id="chart1">
                        <svg style="height:500px;width:100%"></svg>
                    </div>
                </div>

                <div class="col-md-6">
                    <div id="chart2">
                        <svg style="height:500px;width:100%"></svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/plugins/d3/d3.min.js"></script>
    <script src="~/plugins/nvd3/build/nv.d3.min.js"></script>
    <script src="~/Scripts/pages/jquery.nvd3.init.js"></script>

    <script src="~/Scripts/jquery.core.js"></script>
    <script src="~/Scripts/jquery.app.js"></script>
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Views/Chart/Sparkline.cshtml

@{
    ViewBag.Title = "Sparkline";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <ol class="breadcrumb pull-right">
                <li><a href="#">Minton</a></li>
                <li><a href="#">Charts</a></li>
                <li class="active">Sparkline Charts</li>
            </ol>
            <h4 class="page-title">Sparkline Charts</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Line Chart</b></h4>
            <div id="sparkline1"></div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Bar Chart</b></h4>
            <div id="sparkline2" class="text-center"></div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Pie Chart</b></h4>
            <div id="sparkline3" class="text-center"></div>
        </div>
    </div>
</div><!-- Row -->
<div class="row">
    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Custom Line Chart</b></h4>
            <div id="sparkline4" class="text-center"></div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Mouse Speed Chart Example</b></h4>
            <div id="sparkline5" class="text-center"></div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Composite bar Chart</b></h4>
            <div id="sparkline6" class="text-center"></div>
        </div>
    </div>
</div>
<!-- Row -->

@section scripts {
    <!-- Sparkline charts -->
    <script src="~/plugins/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="~/Scripts/pages/jquery.charts-sparkline.js"></script>

    <script src="~/Scripts/jquery.core.js"></script>
    <script src="~/Scripts/jquery.app.js"></script>
}

temp_theming/Minton_v3.0.0/MVC5-Bootstrap-3.3.7/Minton/Views/Extras/EmailTemplate.cshtml
@{
    ViewBag.Title = "EmailTemplate";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <ol class="breadcrumb pull-right">
                <li><a href="#">Minton</a></li>
                <li><a href="#">Extras</a></li>
                <li class="active">Email Templates</li>
            </ol>
            <h4 class="page-title">Email Templates</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-4">
                    <h4 class="m-t-0 m-b-20 header-title"><b>Basic action email</b></h4>
                    <a href="@Url.Action("Action", "Pages")" target="_blank"> <img src="~/images/email/1.png" class="img-responsive" alt=""> </a>
                </div>
                <div class="col-md-4">
                    <h4 class="m-t-0 m-b-20 header-title"><b>Email alert</b> </h4>
                    <a href="@Url.Action("EmailAlert","Pages")" target="_blank"> <img src="~/images/email/2.png" class="img-responsive" alt=""> </a>
                </div>
                <div class="col-md-4">
                    <h4 class="m-t-0 m-b-20 header-title"><b>Billing email</b></h4>
                    <a href="@Url.Action("BillingEmail","Pages")" target="_blank"> <img src="~/images/email/3.png" class="img-responsive" alt=""> </a>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundle/core-app")
}